# Generated by Django 3.0.8 on 2020-07-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Company_Name',
            new_name='Business_Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Female',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Male',
        ),
    ]
